-- Sample artworks data for testing
INSERT INTO artworks (title, artist, date, period, medium, museum, description, image_url) VALUES
('Mona Lisa', 'Leonardo da Vinci', '1503-1519', 'Renaissance', 'Oil on poplar', 'Louvre Museum', 'Portrait of Lisa Gherardini, wife of Francesco del Giocondo', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg/687px-Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg'),
('The Last Supper', 'Leonardo da Vinci', '1495-1498', 'Renaissance', 'Tempera on gesso', 'Santa Maria delle Grazie', 'Depicts the scene of the Last Supper of Jesus with his apostles', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/%C3%9Altima_Cena_-_Da_Vinci_5.jpg/1280px-%C3%9Altima_Cena_-_Da_Vinci_5.jpg'),
('Vitruvian Man', 'Leonardo da Vinci', '1490', 'Renaissance', 'Pen and ink on paper', 'Gallerie dell''Accademia', 'Drawing of a man in two superimposed positions with his arms and legs apart', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Da_Vinci_Vitruve_Luc_Viatour.jpg/694px-Da_Vinci_Vitruve_Luc_Viatour.jpg'),
('Starry Night', 'Vincent van Gogh', '1889', 'Post-Impressionism', 'Oil on canvas', 'Museum of Modern Art', 'A swirling night sky over a village', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg/1280px-Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg'),
('The Great Wave off Kanagawa', 'Katsushika Hokusai', '1831', 'Edo period', 'Woodblock print', 'Metropolitan Museum of Art', 'A large wave threatening boats off the coast of Kanagawa', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/The_Great_Wave_off_Kanagawa.jpg/1280px-The_Great_Wave_off_Kanagawa.jpg'),
('The Persistence of Memory', 'Salvador Dalí', '1931', 'Surrealism', 'Oil on canvas', 'Museum of Modern Art', 'Melting clocks in a dreamlike landscape', 'https://upload.wikimedia.org/wikipedia/en/d/dd/The_Persistence_of_Memory.jpg'),
('Girl with a Pearl Earring', 'Johannes Vermeer', '1665', 'Baroque', 'Oil on canvas', 'Mauritshuis', 'Portrait of a girl with a mysterious pearl earring', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/1665_Girl_with_a_Pearl_Earring.jpg/800px-1665_Girl_with_a_Pearl_Earring.jpg'),
('The Scream', 'Edvard Munch', '1893', 'Expressionism', 'Oil, tempera, and pastel on cardboard', 'National Gallery of Norway', 'An expressionist work depicting a figure with an agonized expression', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Edvard_Munch%2C_1893%2C_The_Scream%2C_oil%2C_tempera_and_pastel_on_cardboard%2C_91_x_73_cm%2C_National_Gallery_of_Norway.jpg/687px-Edvard_Munch%2C_1893%2C_The_Scream%2C_oil%2C_tempera_and_pastel_on_cardboard%2C_91_x_73_cm%2C_National_Gallery_of_Norway.jpg'),
('Guernica', 'Pablo Picasso', '1937', 'Cubism', 'Oil on canvas', 'Museo Reina Sofía', 'Anti-war painting depicting the tragedies of war and the suffering it inflicts', 'https://upload.wikimedia.org/wikipedia/en/7/74/PicassoGuernica.jpg'),
('The Birth of Venus', 'Sandro Botticelli', '1484-1486', 'Renaissance', 'Tempera on canvas', 'Uffizi Gallery', 'Depicts the goddess Venus arriving at the shore after her birth', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg/1280px-Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg');
